server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wedding?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: yyq
    password: 901001
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yyq.wedding.domain
  configuration:
    autoRuntimeDialect: true
