server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://39.105.95.163:3306/wedding?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: Mypwd123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yyq.wedding.domain
  configuration:
    autoRuntimeDialect: true
